Repository otavioalbucosta/Pilgrim, pull requests merged in 2023-06, with the labels that each got.

#1 Poc/passing item
  Pilgrim.xcodeproj/project.pbxproj
  Pilgrim.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Pilgrim/AllStates.swift
  Pilgrim/LocalModel.swift
  Pilgrim/LocalsJSON.json
  Pilgrim/Model/LocalModel.swift
  Pilgrim/Util/JSONReader.swift
  Pilgrim/View/CardView.swift
  Pilgrim/View/SemiCircle.swift
  Pilgrim/View/TinderView.swift
  Pilgrim/Viewmodel/TinderViewmodel.swift
Labels: enhancement

#3 Bug fix/corrigir animacao de passar
  .DS_Store
  Pilgrim.xcodeproj/project.pbxproj
  Pilgrim/View/CardView.swift
  Pilgrim/View/TinderView.swift
Labels: bug

#5 sons de feedback positivo e negativo adicionados
  Pilgrim.xcodeproj/project.pbxproj
  Pilgrim/Resources/feedBackNegativo.mp3
  Pilgrim/Resources/feedBackPositivo.mp3
  Pilgrim/Util/SoundManager.swift
  Pilgrim/Viewmodel/TinderViewmodel.swift
Labels: enhancement

#6 Haptics tateis para sucesso e error adicionado
  Pilgrim.xcodeproj/project.pbxproj
  Pilgrim/Util/HapticsManager.swift
  Pilgrim/Viewmodel/TinderViewmodel.swift
Labels: enhancement

#7 refactor: changing the kfimage constructor
  Pilgrim.xcodeproj/project.pbxproj
  Pilgrim/View/CardView.swift
Labels: bug

#8 Feat/feed view
  Pilgrim.xcodeproj/project.pbxproj
  Pilgrim/PilgrimApp.swift
  Pilgrim/View/Feed/FeedComponentView.swift
  Pilgrim/View/Feed/FeedDetailsView.swift
  Pilgrim/View/Feed/FeedView.swift
  Pilgrim/View/InitialView.swift
  Pilgrim/Viewmodel/FeedViewModel.swift
Labels: enhancement

#10 Feat/persistence data
  Pilgrim.xcodeproj/project.pbxproj
  Pilgrim/Util/JSONReader.swift
  Pilgrim/Util/JSONWrite.swift
  Pilgrim/View/Feed/FeedView.swift
  Pilgrim/Viewmodel/FeedViewModel.swift
  Pilgrim/Viewmodel/TinderViewmodel.swift
Labels: enhancement

#11 funcionalidade implementada já com o UserDefault
  Pilgrim.xcodeproj/project.pbxproj
  Pilgrim/View/TinderView.swift
  Pilgrim/Viewmodel/TinderViewmodel.swift
Labels: enhancement

#14 Feat/feed view
  Pilgrim.xcodeproj/project.pbxproj
  Pilgrim/Model/LocalModel.swift
  Pilgrim/Util/JSONReader.swift
  Pilgrim/View/Feed/FeedComponentView.swift
  Pilgrim/View/Feed/FeedDetailsView.swift
  Pilgrim/View/Feed/FeedView.swift
  Pilgrim/View/InitialView.swift
  Pilgrim/Viewmodel/FeedViewModel.swift
  Pilgrim/Viewmodel/TinderViewmodel.swift
Labels: enhancement

#16 Texto relacionado com o score da partida
  Pilgrim/View/TinderView.swift
Labels: enhancement

#18 fix game center
  GameCenter/GameCenterViewController.swift
  Pilgrim.xcodeproj/project.pbxproj
  Pilgrim/Pilgrim.entitlements
  Pilgrim/View/Feed/FeedView.swift
  Pilgrim/Viewmodel/TinderViewmodel.swift
Labels: enhancement

#17 Sessão de enviar dados para Watch
  Pilgrim Watch App/ContentView.swift
  Pilgrim Watch App/View/FeedWatchView.swift
  Pilgrim Watch App/Viewmodel/FeedWatchViewmodel.swift
  Pilgrim.xcodeproj/project.pbxproj
  Pilgrim/Util/WCSessionManager.swift
  Pilgrim/View/Feed/FeedDetailsView.swift
  Pilgrim/Viewmodel/FeedViewModel.swift
Labels: enhancement

#20 Feat/feed view
  Pilgrim/View/Feed/FeedComponentView.swift
  Pilgrim/View/Feed/FeedDetailsView.swift
  Pilgrim/View/Feed/FeedView.swift
  Pilgrim/Viewmodel/FeedViewModel.swift
  Pilgrim/Viewmodel/TinderViewmodel.swift
Labels: enhancement

#21 funcao para pegar os dados ja esta funcionando
  GameCenter/GameCenterViewController.swift
Labels: enhancement

#22 Refactor/card
  Pilgrim.xcodeproj/project.pbxproj
  Pilgrim.xcodeproj/xcshareddata/xcschemes/Pilgrim.xcscheme
  Pilgrim/View/InitialView.swift
  Pilgrim/View/TinderView.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: enhancement

#24 Update README.md
  README.md
Labels: documentation

#25 Feature/onboarding screen
  Pilgrim.xcodeproj/project.pbxproj
  Pilgrim/Assets.xcassets/ButtonStart.imageset/Button_initial.png
  Pilgrim/Assets.xcassets/ButtonStart.imageset/Contents.json
  Pilgrim/Model/AllStates.swift
  Pilgrim/View/Feed/FeedComponentView.swift
  Pilgrim/View/Game/CardView.swift
  Pilgrim/View/Game/SemiCircle.swift
  Pilgrim/View/Game/TinderView.swift
  Pilgrim/View/InitialView.swift
  Pilgrim/View/Onboarding/FinalOnboardingPageView.swift
  Pilgrim/View/Onboarding/OnboardingPageView.swift
  Pilgrim/View/Onboarding/OnboardingView.swift
  en.lproj/Localizable.strings
Labels: enhancement

#27 agora é apenas possivel ver a onboarding uma vez por instalacao
  Pilgrim/View/InitialView.swift
  Pilgrim/View/Onboarding/OnboardingView.swift
Labels: enhancement

#28 layout do butao ajeitado, coloquei tambem o novo asset do pilgrim na …
  Pilgrim/Assets.xcassets/onboardingPilgrim.imageset/Contents.json
  Pilgrim/Assets.xcassets/onboardingPilgrim.imageset/onboardingPilgrim.png
  Pilgrim/Assets.xcassets/travelButton.imageset/Contents.json
  Pilgrim/Assets.xcassets/travelButton.imageset/travelButton.png
  Pilgrim/View/Onboarding/FinalOnboardingPageView.swift
  Pilgrim/View/Onboarding/OnboardingView.swift
Labels: enhancement
